In [46]:
import sys,os
__script_path=os.path.abspath(globals().get('__file__','.'))
__script_dir = os.path.dirname(__script_path)
root_dir = os.path.abspath(f'{__script_dir}/../../..')
print(root_dir)
for lib in [root_dir][::-1]:
    if lib in sys.path:
        sys.path.remove(lib)
    sys.path.insert(0,lib)

from libs.common import *
from config.config import *

c:\Users\Admin\Data\ads_fraud_detection

# 3. Tiền xử lí dữ liệu

In [47]:
save_dir=f"{exps_dir}/exp2/exp_base"

save_dir = f"{save_dir}"
os.makedirs(save_dir, exist_ok=True)
test_size=0.33
seed=42

In [48]:
from fdb.datasets import FraudDatasetBenchmark

# all_keys = ['fakejob', 'vehicleloan', 'malurl', 'ieeecis', 'ccfraud', 'fraudecom', 'twitterbot', 'ipblock'] 
key = 'vehicleloan'

obj = FraudDatasetBenchmark(
    key=key,
    load_pre_downloaded=False,  # default
    delete_downloaded=True,  # default
    add_random_values_if_real_na = { 
        "EVENT_TIMESTAMP": True, 
        "LABEL_TIMESTAMP": True,
        "ENTITY_ID": True,
        "ENTITY_TYPE": True,
        "ENTITY_ID": True,
        "EVENT_ID": True
        } # default
    )
print(obj.key)

print('Train set: ')
display(obj.train.head())
print(len(obj.train.columns))
print(obj.train.shape)

print('Test set: ')
display(obj.test.head())
print(obj.test.shape)

print('Test scores')
display(obj.test_labels.head())
print(obj.test_labels['EVENT_LABEL'].value_counts())
print(obj.train['EVENT_LABEL'].value_counts(normalize=True))
print('=========')

Data download location c:\Users\Admin\Data\ads_fraud_detection\src\prj2\2.preprocessing\1.base\tmp
vehicleloan
Train set:

       EVENT_ID disbursed_amount asset_cost    ltv branch_id supplier_id manufacturer_id current_pincode_id date_of_birth employment_type state_id employee_code_id mobileno_avl_flag aadhar_flag pan_flag voterid_flag driving_flag passport_flag perform_cns_score perform_cns_score_description pri_no_of_accts pri_active_accts pri_overdue_accts pri_current_balance pri_sanctioned_amount pri_disbursed_amount sec_no_of_accts sec_active_accts sec_overdue_accts sec_current_balance sec_sanctioned_amount sec_disbursed_amount primary_instal_amt sec_instal_amt new_accts_in_last_six_months delinquent_accts_in_last_six_months average_acct_age credit_history_length no_of_inquiries  EVENT_LABEL                             ENTITY_ID       EVENT_TIMESTAMP       LABEL_TIMESTAMP ENTITY_TYPE
8976     462711            33484      62644  55.23        67       22727              45               1511    16-06-1991        Salaried        6             1201                 1           1        0            0            0             0               743               C-Very Low Risk               9                5                 0              160423                230489               194538               0                0                 0                   0                     0                    0               9149              0                            4                                   0        0yrs 7mon             1yrs 4mon               1            0  c3d2fdf8-9e12-4704-9468-edc56024cbb8  2024-08-17T20:08:39Z  2025-02-05T09:45:07Z        user
76007    558674            66882      81187  84.37         2       23508              86               1708    15-09-1994        Salaried        4             1060                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            0  7e1895a9-2ef3-45ae-a579-a31b5487db61  2024-02-16T02:11:13Z  2025-02-05T09:45:07Z        user
77677    528251            59113      71757  84.87        48       21478              86               6322    01-01-1995   Self employed        5             1189                 1           1        0            0            0             0               738               C-Very Low Risk               3                3                 0               45828                 58582                58582               0                0                 0                   0                     0                    0               4240              0                            3                                   0        0yrs 2mon             0yrs 4mon               0            1  bf4e9440-af3a-48af-a6f3-2ad49412a2b8  2024-08-01T02:00:15Z  2025-02-05T09:45:07Z        user
209438   633950            56059      71307  81.34       146       18317              86               2989    01-01-1971        Salaried       14             2964                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            1  ddbc86a8-57a8-4d40-bf4e-c4508900e48f  2024-02-26T14:43:42Z  2025-02-05T09:45:07Z        user
143261   476747            56759      67100  85.69       136       17783              86               3793    03-12-1975   Self employed        8             1295                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            0  2f3859de-48e8-4265-8473-be48d16e7c83  2024-03-03T10:09:00Z  2025-02-05T09:45:07Z        user

44
(186523, 44)
Test set:

  EVENT_ID disbursed_amount asset_cost    ltv branch_id supplier_id manufacturer_id current_pincode_id date_of_birth employment_type state_id employee_code_id mobileno_avl_flag aadhar_flag pan_flag voterid_flag driving_flag passport_flag perform_cns_score                      perform_cns_score_description pri_no_of_accts pri_active_accts pri_overdue_accts pri_current_balance pri_sanctioned_amount pri_disbursed_amount sec_no_of_accts sec_active_accts sec_overdue_accts sec_current_balance sec_sanctioned_amount sec_disbursed_amount primary_instal_amt sec_instal_amt new_accts_in_last_six_months delinquent_accts_in_last_six_months average_acct_age credit_history_length no_of_inquiries                             ENTITY_ID       EVENT_TIMESTAMP ENTITY_TYPE
0   420825            50578      58400  89.55        67       22807              45               1441    01-01-1984        Salaried        6             1998                 1           1        0            0            0             0                 0                        No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0  b8ee6f6f-c11d-4e81-b893-ea228e0da63f  2024-12-18T06:06:48Z        user
1   518279            54513      61900  89.66        67       22807              45               1501    08-09-1990   Self employed        6             1998                 1           1        0            0            0             0               825                                    A-Very Low Risk               2                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0               1347              0                            0                                   0        1yrs 9mon             2yrs 0mon               0  b347c00c-dabb-42a9-8ab9-e652b716797f  2024-05-29T09:31:39Z        user
2   510278            43894      61900  71.89        67       22807              45               1501    04-10-1989        Salaried        6             1998                 1           1        0            0            0             0                17  Not Scored: Not Enough Info available on the c...               1                1                 0               72879                 74500                74500               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 2mon             0yrs 2mon               0  c62ce521-d1ce-480e-81b2-aa27e37d78df  2024-02-21T10:37:17Z        user
3   510980            52603      61300  86.95        67       22807              45               1492    01-06-1968        Salaried        6             1998                 1           0        0            1            0             0               818                                    A-Very Low Risk               1                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0               2608              0                            0                                   0        1yrs 7mon             1yrs 7mon               0  5cc7b925-8963-4baa-b0c6-cc4285622c10  2024-10-06T14:55:57Z        user
4   513916            57713      65750  89.28        67       22807              45               1440    01-06-1976   Self employed        6             1998                 1           1        0            0            0             0               300                                   M-Very High Risk               6                4                 2               29069               1067200              1067200               0                0                 0                   0                     0                    0              47100              0                            1                                   1        2yrs 6mon             5yrs 6mon               0  d01ad509-e82d-4aab-a559-4f63f98d0cd8  2024-02-21T00:05:15Z        user

(46631, 42)
Test scores

   EVENT_LABEL
0            0
1            0
2            0
3            0
4            0

EVENT_LABEL
0    36323
1    10308
Name: count, dtype: int64
EVENT_LABEL
0    0.783925
1    0.216075
Name: proportion, dtype: float64
=========

In [49]:
test_size=0.33
seed=42
train=obj.train
test=obj.test
train

       EVENT_ID disbursed_amount asset_cost    ltv branch_id supplier_id manufacturer_id current_pincode_id date_of_birth employment_type state_id employee_code_id mobileno_avl_flag aadhar_flag pan_flag voterid_flag driving_flag passport_flag perform_cns_score perform_cns_score_description pri_no_of_accts pri_active_accts pri_overdue_accts pri_current_balance pri_sanctioned_amount pri_disbursed_amount sec_no_of_accts sec_active_accts sec_overdue_accts sec_current_balance sec_sanctioned_amount sec_disbursed_amount primary_instal_amt sec_instal_amt new_accts_in_last_six_months delinquent_accts_in_last_six_months average_acct_age credit_history_length no_of_inquiries  EVENT_LABEL                             ENTITY_ID       EVENT_TIMESTAMP       LABEL_TIMESTAMP ENTITY_TYPE
8976     462711            33484      62644  55.23        67       22727              45               1511    16-06-1991        Salaried        6             1201                 1           1        0            0            0             0               743               C-Very Low Risk               9                5                 0              160423                230489               194538               0                0                 0                   0                     0                    0               9149              0                            4                                   0        0yrs 7mon             1yrs 4mon               1            0  c3d2fdf8-9e12-4704-9468-edc56024cbb8  2024-08-17T20:08:39Z  2025-02-05T09:45:07Z        user
76007    558674            66882      81187  84.37         2       23508              86               1708    15-09-1994        Salaried        4             1060                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            0  7e1895a9-2ef3-45ae-a579-a31b5487db61  2024-02-16T02:11:13Z  2025-02-05T09:45:07Z        user
77677    528251            59113      71757  84.87        48       21478              86               6322    01-01-1995   Self employed        5             1189                 1           1        0            0            0             0               738               C-Very Low Risk               3                3                 0               45828                 58582                58582               0                0                 0                   0                     0                    0               4240              0                            3                                   0        0yrs 2mon             0yrs 4mon               0            1  bf4e9440-af3a-48af-a6f3-2ad49412a2b8  2024-08-01T02:00:15Z  2025-02-05T09:45:07Z        user
209438   633950            56059      71307  81.34       146       18317              86               2989    01-01-1971        Salaried       14             2964                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            1  ddbc86a8-57a8-4d40-bf4e-c4508900e48f  2024-02-26T14:43:42Z  2025-02-05T09:45:07Z        user
143261   476747            56759      67100  85.69       136       17783              86               3793    03-12-1975   Self employed        8             1295                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            0  2f3859de-48e8-4265-8473-be48d16e7c83  2024-03-03T10:09:00Z  2025-02-05T09:45:07Z        user
...         ...              ...        ...    ...       ...         ...             ...                ...           ...             ...      ...              ...               ...         ...      ...          ...          ...           ...               ...                           ...             ...              ...               ...                 ...                   ...                  ...             ...              ...               ...                 ...                   ...                  ...                ...            ...                          ...                                 ...              ...                   ...             ...          ...                                   ...                   ...                   ...         ...
184470   643379            55549      82230  70.78        36       22408              45               6648    01-01-1992   Self employed       13             2461                 1           0        0            1            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            0  a983e839-fd7e-495f-845e-5d505653d6c9  2024-08-18T23:39:07Z  2025-02-05T09:45:07Z        user
13925    587710            60213      71857  84.89       147       17705              45               2782    01-01-1981        Salaried        2             1664                 1           1        0            0            0             0                 0   No Bureau History Available               0                0                 0                   0                     0                    0               0                0                 0                   0                     0                    0                  0              0                            0                                   0        0yrs 0mon             0yrs 0mon               0            0  16ecc203-6593-433c-a3d6-cf86246f5b1b  2024-10-23T05:50:43Z  2025-02-05T09:45:07Z        user
113781   636081            52328      68757  78.54        74       22229              45               2578    30-06-1994   Self employed        4             1467                 1           1        0            0            1             0               300              M-Very High Risk               2                2                 1              107853                177000               177000               0                0                 0                   0                     0                    0               1732              0                            0                                   0        1yrs 5mon             1yrs 9mon               0            0  60d4f392-7cb1-4ca6-9964-ce2b229fd2c5  2024-02-22T04:07:45Z  2025-02-05T09:45:07Z        user
128320   431351            77579     100360  79.71        34       22891              51               1001    28-05-1966        Salaried        6             1633                 1           1        0            0            0             0               407                   K-High Risk              20               10                 6             4712581               5277128              5418148               0                0                 0                   0                     0                    0              49484              0                            0                                   6        4yrs 5mon            15yrs 5mon               1            0  a99082ad-7135-4544-af90-28c704320a4d  2024-04-19T17:59:35Z  2025-02-05T09:45:07Z        user
139992   508891            57140      75440  79.97         5       14145              86               3356    04-05-1985        Salaried        9              326                 1           0        0            0            0             1               300              M-Very High Risk               1                0                 1                   0                     0                    0               2                1                 1              199979                243000               243000                  0              0                            0                                   0        0yrs 8mon             1yrs 4mon               1            0  131acbe7-b4d8-4925-9db0-e83f8a2b2f99  2024-11-23T14:56:57Z  2025-02-05T09:45:07Z        user

[186523 rows x 44 columns]

In [50]:
train =train.rename(columns=lambda x: x.upper())
test =test.rename(columns=lambda x: x.upper())

In [51]:
train.columns

Index(['EVENT_ID', 'DISBURSED_AMOUNT', 'ASSET_COST', 'LTV', 'BRANCH_ID', 'SUPPLIER_ID', 'MANUFACTURER_ID', 'CURRENT_PINCODE_ID', 'DATE_OF_BIRTH', 'EMPLOYMENT_TYPE', 'STATE_ID', 'EMPLOYEE_CODE_ID', 'MOBILENO_AVL_FLAG', 'AADHAR_FLAG', 'PAN_FLAG', 'VOTERID_FLAG', 'DRIVING_FLAG', 'PASSPORT_FLAG', 'PERFORM_CNS_SCORE', 'PERFORM_CNS_SCORE_DESCRIPTION', 'PRI_NO_OF_ACCTS', 'PRI_ACTIVE_ACCTS', 'PRI_OVERDUE_ACCTS', 'PRI_CURRENT_BALANCE', 'PRI_SANCTIONED_AMOUNT', 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_ACTIVE_ACCTS', 'SEC_OVERDUE_ACCTS', 'SEC_CURRENT_BALANCE', 'SEC_SANCTIONED_AMOUNT', 'SEC_DISBURSED_AMOUNT', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT', 'NEW_ACCTS_IN_LAST_SIX_MONTHS', 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'AVERAGE_ACCT_AGE', 'CREDIT_HISTORY_LENGTH', 'NO_OF_INQUIRIES', 'EVENT_LABEL', 'ENTITY_ID', 'EVENT_TIMESTAMP', 'LABEL_TIMESTAMP', 'ENTITY_TYPE'], dtype='object')

In [52]:
#Number of observations in column
obs = len(train.DISBURSED_AMOUNT)
print("No. of observations in column: ",obs)
train['DISBURSED_AMOUNT'] = pd.to_numeric(train['DISBURSED_AMOUNT'], errors='coerce')

# calculate summary statistics
data_mean, data_std = mean(train.DISBURSED_AMOUNT), std(train.DISBURSED_AMOUNT)
print('Statistics: Mean=%.3f, Std dev=%.3f' % (data_mean, data_std))
# identify outliers
cut_off = data_std * 3
lower, upper = data_mean - cut_off, data_mean + cut_off
# identify outliers
outliers = [x for x in train.DISBURSED_AMOUNT if x < lower or x > upper]
print('Identified outliers: %d' % len(outliers))

No. of observations in column:  186523
Statistics: Mean=54340.127, Std dev=13021.099
Identified outliers: 2469

In [53]:
def impute_outlier(x):
    if x <= lower:
        return(data_mean)
    elif x>= (upper):
        return(data_mean)
    else:
        return(x)
train["DISBURSED_AMOUNT_new"]= train["DISBURSED_AMOUNT"].apply(impute_outlier)
print("No. of observations in column: ",len(train.DISBURSED_AMOUNT_new))

No. of observations in column:  186523

In [54]:
bin_labels = ['Low', 'Medium', 'High', 'Extreme']
train['DISBURSED_AMOUNT_bins'] = pd.qcut(train['DISBURSED_AMOUNT'],
                              q=[0, .25, .5, .75, 1],
                              labels=bin_labels)
train['DISBURSED_AMOUNT_bins'].value_counts()

DISBURSED_AMOUNT_bins
Medium     46924
Low        46888
Extreme    46588
High       46123
Name: count, dtype: int64

In [55]:
#Number of observations in column
def outlier_data(df, feature):
    #Number of observations in column
    obs = len(df[feature])
    print("No. of observations in column: ",obs)

    # calculate summary statistics
    data_mean, data_std = mean(df[feature]), std(df[feature])
    print('Statistics: Mean=%.3f, Std dev=%.3f' % (data_mean, data_std))
    # identify outliers
    cut_off = data_std * 3
    lower, upper = data_mean - cut_off, data_mean + cut_off
    # identify outliers
    outliers = [x for x in df[feature] if x < lower or x > upper]
    print('Identified outliers: %d' % len(outliers))

def impute_outlier(x):
    if x <= lower:
        return(data_mean)
    elif x>= (upper):
        return(data_mean)
    else:
        return(x)

In [56]:
train['LTV'] = pd.to_numeric(train['LTV'], errors='coerce')
outlier_data(train,"LTV")
train["LTV_new"]= train["LTV"].apply(impute_outlier)
print("No. of observations in column: ",len(train.DISBURSED_AMOUNT_new))
outlier_data(train,"LTV_new")

No. of observations in column:  186523
Statistics: Mean=74.745, Std dev=11.446
Identified outliers: 2181
No. of observations in column:  186523
No. of observations in column:  186523
Statistics: Mean=54340.127, Std dev=0.000
Identified outliers: 0

In [57]:
train['ASSET_COST'] = pd.to_numeric(train['ASSET_COST'], errors='coerce')
outlier_data(train,"ASSET_COST")
train["ASSET_COST_new"]= train["ASSET_COST"].apply(impute_outlier)
print("No. of observations in column: ",len(train.DISBURSED_AMOUNT_new))
outlier_data(train,"ASSET_COST_new")

No. of observations in column:  186523
Statistics: Mean=75835.490, Std dev=18998.475
Identified outliers: 3531
No. of observations in column:  186523
No. of observations in column:  186523
Statistics: Mean=68037.630, Std dev=9609.975
Identified outliers: 44

In [58]:
train.columns

Index(['EVENT_ID', 'DISBURSED_AMOUNT', 'ASSET_COST', 'LTV', 'BRANCH_ID', 'SUPPLIER_ID', 'MANUFACTURER_ID', 'CURRENT_PINCODE_ID', 'DATE_OF_BIRTH', 'EMPLOYMENT_TYPE', 'STATE_ID', 'EMPLOYEE_CODE_ID', 'MOBILENO_AVL_FLAG', 'AADHAR_FLAG', 'PAN_FLAG', 'VOTERID_FLAG', 'DRIVING_FLAG', 'PASSPORT_FLAG', 'PERFORM_CNS_SCORE', 'PERFORM_CNS_SCORE_DESCRIPTION', 'PRI_NO_OF_ACCTS', 'PRI_ACTIVE_ACCTS', 'PRI_OVERDUE_ACCTS', 'PRI_CURRENT_BALANCE', 'PRI_SANCTIONED_AMOUNT', 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_ACTIVE_ACCTS', 'SEC_OVERDUE_ACCTS', 'SEC_CURRENT_BALANCE', 'SEC_SANCTIONED_AMOUNT', 'SEC_DISBURSED_AMOUNT', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT', 'NEW_ACCTS_IN_LAST_SIX_MONTHS', 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'AVERAGE_ACCT_AGE', 'CREDIT_HISTORY_LENGTH', 'NO_OF_INQUIRIES', 'EVENT_LABEL', 'ENTITY_ID', 'EVENT_TIMESTAMP', 'LABEL_TIMESTAMP', 'ENTITY_TYPE', 'DISBURSED_AMOUNT_new', 'DISBURSED_AMOUNT_bins', 'LTV_new', 'ASSET_COST_new'], dtype='object')

In [59]:
now = pd.Timestamp('now')
#train['DATE_OF_BIRTH'] = train['DATE_OF_BIRTH'].where(train['DATE_OF_BIRTH'] < now, train['DATE_OF_BIRTH'] -  np.timedelta64(100, 'Y'))   
train['DATE_OF_BIRTH'] = pd.to_datetime(train['DATE_OF_BIRTH'], errors='coerce')
train['age'] = (now - train['DATE_OF_BIRTH'])  

train['age']= train['age'].astype(str)
train[['age','age_waste']] = train['age'].str.split("days",expand=True)
train['age']= train['age'].astype(str).astype(int)
train= train.drop(columns= ['age_waste'])

print(train['age'].head())

8976      12288
76007     11101
77677     10993
209438    19759
143261    17962
Name: age, dtype: int32

In [60]:
train_con = train[['EMPLOYMENT_TYPE', 'MOBILENO_AVL_FLAG', 'AADHAR_FLAG', 'PAN_FLAG', 'VOTERID_FLAG',
                   'DRIVING_FLAG', 'PASSPORT_FLAG', 'PERFORM_CNS_SCORE', 'PERFORM_CNS_SCORE_DESCRIPTION', 
                   'PRI_ACTIVE_ACCTS', 'PRI_CURRENT_BALANCE', 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 
                   'SEC_OVERDUE_ACCTS', 'SEC_CURRENT_BALANCE', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT', 
                   'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'CREDIT_HISTORY_LENGTH', 'NO_OF_INQUIRIES',
                   'EVENT_LABEL', 'DISBURSED_AMOUNT_new', 'ASSET_COST_new', 
                   'LTV_new', 'age']]

In [61]:
test.EVENT_ID

0        420825
1        518279
2        510278
3        510980
4        513916
          ...
46626    585873
46627    497980
46628    623179
46629    613161
46630    613658
Name: EVENT_ID, Length: 46631, dtype: object

In [62]:
#Number of observations in column
obs = len(test.DISBURSED_AMOUNT)
print("No. of observations in column: ",obs)
test['DISBURSED_AMOUNT'] = pd.to_numeric(test['DISBURSED_AMOUNT'], errors='coerce')

# calculate summary statistics
data_mean, data_std = mean(test.DISBURSED_AMOUNT), std(test.DISBURSED_AMOUNT)
print('Statistics: Mean=%.3f, Std dev=%.3f' % (data_mean, data_std))
# identify outliers
cut_off = data_std * 3
lower, upper = data_mean - cut_off, data_mean + cut_off
# identify outliers
outliers = [x for x in test.DISBURSED_AMOUNT if x < lower or x > upper]
print('Identified outliers: %d' % len(outliers))
def impute_outlier(x):
    if x <= lower:
        return(data_mean)
    elif x>= (upper):
        return(data_mean)
    else:
        return(x)
test["DISBURSED_AMOUNT_new"]= test["DISBURSED_AMOUNT"].apply(impute_outlier)
print("No. of observations in column: ",len(test.DISBURSED_AMOUNT_new))
bin_labels = ['Low', 'Medium', 'High', 'Extreme']
test['DISBURSED_AMOUNT_bins'] = pd.qcut(test['DISBURSED_AMOUNT'],
                              q=[0, .25, .5, .75, 1],
                              labels=bin_labels)
test['DISBURSED_AMOUNT_bins'].value_counts()
test['LTV'] = pd.to_numeric(test['LTV'], errors='coerce')
outlier_data(test,"LTV")
test["LTV_new"]= test["LTV"].apply(impute_outlier)
print("No. of observations in column: ",len(test.DISBURSED_AMOUNT_new))
outlier_data(test,"LTV_new")
test['ASSET_COST'] = pd.to_numeric(test['ASSET_COST'], errors='coerce')
outlier_data(test,"ASSET_COST")
test["ASSET_COST_new"]= test["ASSET_COST"].apply(impute_outlier)
print("No. of observations in column: ",len(test.DISBURSED_AMOUNT_new))
outlier_data(test,"ASSET_COST_new")
now = pd.Timestamp('now')
#test['DATE_OF_BIRTH'] = test['DATE_OF_BIRTH'].where(test['DATE_OF_BIRTH'] < now, test['DATE_OF_BIRTH'] -  np.timedelta64(100, 'Y'))   
test['DATE_OF_BIRTH'] = pd.to_datetime(test['DATE_OF_BIRTH'], errors='coerce')
test['age'] = (now - test['DATE_OF_BIRTH'])  

test['age']= test['age'].astype(str)
test[['age','age_waste']] = test['age'].str.split("days",expand=True)
test['age'] = test['age'].replace('NaT', '0')  # Thay NaT bằng '0'
test['age'] = test['age'].astype(int) 
test['age']= test['age'].astype(str).astype(int)
test= test.drop(columns= ['age_waste'])

print(test['age'].head())

No. of observations in column:  46631
Statistics: Mean=54424.459, Std dev=12769.871
Identified outliers: 625
No. of observations in column:  46631
No. of observations in column:  46631
Statistics: Mean=74.751, Std dev=11.498
Identified outliers: 564
No. of observations in column:  46631
No. of observations in column:  46631
Statistics: Mean=54424.459, Std dev=0.000
Identified outliers: 0
No. of observations in column:  46631
Statistics: Mean=75983.381, Std dev=18727.794
Identified outliers: 904
No. of observations in column:  46631
No. of observations in column:  46631
Statistics: Mean=67932.564, Std dev=9548.140
Identified outliers: 10
0    15011
1    12599
2    13085
3    20850
4    17928
Name: age, dtype: int32

In [63]:
test.columns

Index(['EVENT_ID', 'DISBURSED_AMOUNT', 'ASSET_COST', 'LTV', 'BRANCH_ID', 'SUPPLIER_ID', 'MANUFACTURER_ID', 'CURRENT_PINCODE_ID', 'DATE_OF_BIRTH', 'EMPLOYMENT_TYPE', 'STATE_ID', 'EMPLOYEE_CODE_ID', 'MOBILENO_AVL_FLAG', 'AADHAR_FLAG', 'PAN_FLAG', 'VOTERID_FLAG', 'DRIVING_FLAG', 'PASSPORT_FLAG', 'PERFORM_CNS_SCORE', 'PERFORM_CNS_SCORE_DESCRIPTION', 'PRI_NO_OF_ACCTS', 'PRI_ACTIVE_ACCTS', 'PRI_OVERDUE_ACCTS', 'PRI_CURRENT_BALANCE', 'PRI_SANCTIONED_AMOUNT', 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_ACTIVE_ACCTS', 'SEC_OVERDUE_ACCTS', 'SEC_CURRENT_BALANCE', 'SEC_SANCTIONED_AMOUNT', 'SEC_DISBURSED_AMOUNT', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT', 'NEW_ACCTS_IN_LAST_SIX_MONTHS', 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'AVERAGE_ACCT_AGE', 'CREDIT_HISTORY_LENGTH', 'NO_OF_INQUIRIES', 'ENTITY_ID', 'EVENT_TIMESTAMP', 'ENTITY_TYPE', 'DISBURSED_AMOUNT_new', 'DISBURSED_AMOUNT_bins', 'LTV_new', 'ASSET_COST_new', 'age'], dtype='object')

In [64]:
test = pd.concat([test, obj.test_labels['EVENT_LABEL']], axis=1)
test_con = test[['EMPLOYMENT_TYPE', 'MOBILENO_AVL_FLAG', 'AADHAR_FLAG', 'PAN_FLAG', 'VOTERID_FLAG',
                   'DRIVING_FLAG', 'PASSPORT_FLAG', 'PERFORM_CNS_SCORE', 'PERFORM_CNS_SCORE_DESCRIPTION', 
                   'PRI_ACTIVE_ACCTS', 'PRI_CURRENT_BALANCE', 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 
                   'SEC_OVERDUE_ACCTS', 'SEC_CURRENT_BALANCE', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT', 
                   'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'CREDIT_HISTORY_LENGTH', 'NO_OF_INQUIRIES',
                   'EVENT_LABEL', 'DISBURSED_AMOUNT_new', 'ASSET_COST_new', 
                   'LTV_new', 'age']]

In [67]:
missing_columns = set(train.columns) - set(test.columns)
print("Các cột có trong train nhưng không có trong test:", missing_columns)
train.drop(columns=missing_columns, inplace=True)

Các cột có trong train nhưng không có trong test: {'LABEL_TIMESTAMP'}

In [72]:
columns_to_convert = [
    'PERFORM_CNS_SCORE', 'PRI_ACTIVE_ACCTS', 'PRI_CURRENT_BALANCE', 
    'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_OVERDUE_ACCTS', 
    'SEC_CURRENT_BALANCE', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT',
    'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'CREDIT_HISTORY_LENGTH', 
    'NO_OF_INQUIRIES', 'DISBURSED_AMOUNT_new',
    'ASSET_COST_new', 'LTV_new', 'age'
]

for col in columns_to_convert:
    train[col] = pd.to_numeric(train[col], errors='coerce')
    test[col] = pd.to_numeric(test[col], errors='coerce')

print(train.dtypes)

EVENT_ID                                       object
DISBURSED_AMOUNT                                int64
ASSET_COST                                      int64
LTV                                           float64
BRANCH_ID                                      object
SUPPLIER_ID                                    object
MANUFACTURER_ID                                object
CURRENT_PINCODE_ID                             object
DATE_OF_BIRTH                          datetime64[ns]
EMPLOYMENT_TYPE                                object
STATE_ID                                       object
EMPLOYEE_CODE_ID                               object
MOBILENO_AVL_FLAG                              object
AADHAR_FLAG                                    object
PAN_FLAG                                       object
VOTERID_FLAG                                   object
DRIVING_FLAG                                   object
PASSPORT_FLAG                                  object
PERFORM_CNS_SCORE                               int64
PERFORM_CNS_SCORE_DESCRIPTION                  object
PRI_NO_OF_ACCTS                                object
PRI_ACTIVE_ACCTS                                int64
PRI_OVERDUE_ACCTS                              object
PRI_CURRENT_BALANCE                             int64
PRI_SANCTIONED_AMOUNT                          object
PRI_DISBURSED_AMOUNT                            int64
SEC_NO_OF_ACCTS                                 int64
SEC_ACTIVE_ACCTS                               object
SEC_OVERDUE_ACCTS                               int64
SEC_CURRENT_BALANCE                             int64
SEC_SANCTIONED_AMOUNT                          object
SEC_DISBURSED_AMOUNT                           object
PRIMARY_INSTAL_AMT                              int64
SEC_INSTAL_AMT                                  int64
NEW_ACCTS_IN_LAST_SIX_MONTHS                   object
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS             int64
AVERAGE_ACCT_AGE                               object
CREDIT_HISTORY_LENGTH                         float64
NO_OF_INQUIRIES                                 int64
EVENT_LABEL                                     int32
ENTITY_ID                                      object
EVENT_TIMESTAMP                                object
ENTITY_TYPE                                    object
DISBURSED_AMOUNT_new                          float64
DISBURSED_AMOUNT_bins                        category
LTV_new                                       float64
ASSET_COST_new                                float64
age                                             int32
dtype: object

In [74]:
category_columns = train.select_dtypes(include=['object']).columns
print("Categorical columns: ", category_columns)
numeric_columns = train.select_dtypes(include=['int64', 'float64']).columns
print("Numerical columns: ", numeric_columns)
np.savez(f'{save_dir}/columns_dtype.npz', category_columns = category_columns, numeric_columns = numeric_columns)

Categorical columns:  Index(['EVENT_ID', 'BRANCH_ID', 'SUPPLIER_ID', 'MANUFACTURER_ID', 'CURRENT_PINCODE_ID', 'EMPLOYMENT_TYPE', 'STATE_ID', 'EMPLOYEE_CODE_ID', 'MOBILENO_AVL_FLAG', 'AADHAR_FLAG', 'PAN_FLAG', 'VOTERID_FLAG', 'DRIVING_FLAG', 'PASSPORT_FLAG', 'PERFORM_CNS_SCORE_DESCRIPTION', 'PRI_NO_OF_ACCTS', 'PRI_OVERDUE_ACCTS', 'PRI_SANCTIONED_AMOUNT', 'SEC_ACTIVE_ACCTS', 'SEC_SANCTIONED_AMOUNT', 'SEC_DISBURSED_AMOUNT', 'NEW_ACCTS_IN_LAST_SIX_MONTHS', 'AVERAGE_ACCT_AGE', 'ENTITY_ID', 'EVENT_TIMESTAMP', 'ENTITY_TYPE'], dtype='object')
Numerical columns:  Index(['DISBURSED_AMOUNT', 'ASSET_COST', 'LTV', 'PERFORM_CNS_SCORE', 'PRI_ACTIVE_ACCTS', 'PRI_CURRENT_BALANCE', 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_OVERDUE_ACCTS', 'SEC_CURRENT_BALANCE', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT', 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'CREDIT_HISTORY_LENGTH', 'NO_OF_INQUIRIES', 'DISBURSED_AMOUNT_new', 'LTV_new', 'ASSET_COST_new'], dtype='object')

In [76]:
test.isnull().sum()

EVENT_ID                                   0
DISBURSED_AMOUNT                           0
ASSET_COST                                 0
LTV                                        0
BRANCH_ID                                  0
SUPPLIER_ID                                0
MANUFACTURER_ID                            0
CURRENT_PINCODE_ID                         0
DATE_OF_BIRTH                          17229
EMPLOYMENT_TYPE                         1548
STATE_ID                                   0
EMPLOYEE_CODE_ID                           0
MOBILENO_AVL_FLAG                          0
AADHAR_FLAG                                0
PAN_FLAG                                   0
VOTERID_FLAG                               0
DRIVING_FLAG                               0
PASSPORT_FLAG                              0
PERFORM_CNS_SCORE                          0
PERFORM_CNS_SCORE_DESCRIPTION              0
PRI_NO_OF_ACCTS                            0
PRI_ACTIVE_ACCTS                           0
PRI_OVERDUE_ACCTS                          0
PRI_CURRENT_BALANCE                        0
PRI_SANCTIONED_AMOUNT                      0
PRI_DISBURSED_AMOUNT                       0
SEC_NO_OF_ACCTS                            0
SEC_ACTIVE_ACCTS                           0
SEC_OVERDUE_ACCTS                          0
SEC_CURRENT_BALANCE                        0
SEC_SANCTIONED_AMOUNT                      0
SEC_DISBURSED_AMOUNT                       0
PRIMARY_INSTAL_AMT                         0
SEC_INSTAL_AMT                             0
NEW_ACCTS_IN_LAST_SIX_MONTHS               0
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS        0
AVERAGE_ACCT_AGE                           0
CREDIT_HISTORY_LENGTH                  46631
NO_OF_INQUIRIES                            0
ENTITY_ID                                  0
EVENT_TIMESTAMP                            0
ENTITY_TYPE                                0
DISBURSED_AMOUNT_new                       0
DISBURSED_AMOUNT_bins                      0
LTV_new                                    0
ASSET_COST_new                             0
age                                        0
EVENT_LABEL                                0
dtype: int64

In [35]:
# Confusion Matrix

def plot_confusion_matrix(cm, classes,
                          normalize = False,
                          title = 'Confusion matrix"',
                          cmap = plt.cm.Blues) :
    plt.imshow(cm, interpolation = 'nearest', cmap = cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation = 0)
    plt.yticks(tick_marks, classes)

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])) :
        plt.text(j, i, cm[i, j],
                 horizontalalignment = 'center',
                 color = 'white' if cm[i, j] > thresh else 'black')

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [36]:
scaler_data = StandardScaler() 
def scaleColumns(df, cols_to_scale):

    for col in cols_to_scale:

        df[col] = pd.DataFrame(scaler_data.fit_transform(pd.DataFrame(train_con[col])),columns=[col])

    return df

In [38]:
train_con

       EMPLOYMENT_TYPE MOBILENO_AVL_FLAG AADHAR_FLAG PAN_FLAG VOTERID_FLAG DRIVING_FLAG PASSPORT_FLAG  PERFORM_CNS_SCORE PERFORM_CNS_SCORE_DESCRIPTION  PRI_ACTIVE_ACCTS  PRI_CURRENT_BALANCE  PRI_DISBURSED_AMOUNT  SEC_NO_OF_ACCTS  SEC_OVERDUE_ACCTS  SEC_CURRENT_BALANCE  PRIMARY_INSTAL_AMT  SEC_INSTAL_AMT  DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS CREDIT_HISTORY_LENGTH NO_OF_INQUIRIES  EVENT_LABEL  DISBURSED_AMOUNT_new  ASSET_COST_new       LTV_new    age
8976          Salaried                 1           1        0            0            0             0          -0.855060               C-Very Low Risk         -0.533268            -0.178010             -0.181889        -0.093996          -0.066024            -0.032864           -0.087314       -0.020499                            -0.252023             1yrs 4mon               1            0               33484.0    62644.000000  54340.127169  12288
76007         Salaried                 1           1        0            0            0             0           1.582579   No Bureau History Available         -0.533268            -0.178010             -0.181889        -0.093996          -0.066024            -0.032864           -0.079539       -0.020499                            -0.252023             0yrs 0mon               0            0               66882.0    81187.000000  54340.127169  11101
77677    Self employed                 1           1        0            0            0             0           1.322564               C-Very Low Risk         -0.020235            -0.162858             -0.149818        -0.093996          -0.066024            -0.032864           -0.070343       -0.020499                            -0.252023             0yrs 4mon               0            1               59113.0    71757.000000  54340.127169  10993
209438        Salaried                 1           1        0            0            0             0                NaN   No Bureau History Available               NaN                  NaN                   NaN              NaN                NaN                  NaN                 NaN             NaN                                  NaN             0yrs 0mon               0            1               56059.0    71307.000000  54340.127169  19759
143261   Self employed                 1           1        0            0            0             0           1.322564   No Bureau History Available          0.492797            -0.129962             -0.133548        -0.093996          -0.066024            -0.032864           -0.076981       -0.020499                            -0.252023             0yrs 0mon               0            0               56759.0    67100.000000  54340.127169  17962
...                ...               ...         ...      ...          ...          ...           ...                ...                           ...               ...                  ...                   ...              ...                ...                  ...                 ...             ...                                  ...                   ...             ...          ...                   ...             ...           ...    ...
184470   Self employed                 1           0        0            1            0             0           1.623945   No Bureau History Available          0.492797            -0.063174              0.414313        -0.093996          -0.066024            -0.032864            0.051812       -0.020499                            -0.252023             0yrs 0mon               0            0               55549.0    82230.000000  54340.127169  12089
13925         Salaried                 1           1        0            0            0             0          -0.855060   No Bureau History Available         -0.533268            -0.178010             -0.181889        -0.093996          -0.066024            -0.032864           -0.087314       -0.020499                            -0.252023             0yrs 0mon               0            0               60213.0    71857.000000  54340.127169  16106
113781   Self employed                 1           1        0            0            1             0          -0.855060              M-Very High Risk         -0.533268            -0.178010             -0.181889        -0.093996          -0.066024            -0.032864           -0.087314       -0.020499                            -0.252023             1yrs 9mon               0            0               52328.0    68757.000000  54340.127169  11178
128320        Salaried                 1           1        0            0            0             0          -0.855060                   K-High Risk         -0.533268            -0.178010             -0.181889        -0.093996          -0.066024            -0.032864           -0.087314       -0.020499                            -0.252023            15yrs 5mon               1            0               77579.0    54340.127169  54340.127169  21438
139992        Salaried                 1           0        0            0            0             1          -0.855060              M-Very High Risk         -0.533268            -0.178010             -0.181889        -0.093996          -0.066024            -0.032864           -0.087314       -0.020499                            -0.252023             1yrs 4mon               1            0               57140.0    75440.000000  54340.127169  14522

[186523 rows x 25 columns]

In [37]:
scaled_df = scaleColumns(train_con,['PERFORM_CNS_SCORE','PRI_ACTIVE_ACCTS', 'PRI_CURRENT_BALANCE', 
                                 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_OVERDUE_ACCTS', 
                                 'SEC_CURRENT_BALANCE', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT',
                                 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'CREDIT_HISTORY_LENGTH', 
                                 'NO_OF_INQUIRIES', 'DISBURSED_AMOUNT_new',
                                 'ASSET_COST_new', 'LTV_new', 'age', 'disbursal_time'])

scaled_df.head()

ValueError: could not convert string to float: '1yrs 4mon'

In [ ]:
train_dummy = pd.get_dummies(scaled_df, prefix_sep='_', drop_first=True)
train_dummy.head()

In [ ]:
y = train_dummy[['LOAN_DEFAULT']]
X= train_dummy.loc[:, train_dummy.columns != 'LOAN_DEFAULT']
X.shape

In [ ]:
X = X.fillna(0)
X.shape

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(X, y, test_size = 0.20, random_state = 101)
x_train.to_csv(f'{save_dir}/x_train.csv', index=False)
y_train.to_csv(f'{save_dir}/y_train.csv', index=False)
x_valid.to_csv(f'{save_dir}/x_valid.csv', index=False)
y_valid.to_csv(f'{save_dir}/y_valid.csv', index=False)

In [13]:
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
class_weights_dict = {i : class_weights[i] for i in range(len(class_weights))}
np.savez(f'{save_dir}/class_weights_dict.npz', class_weights_dict = class_weights_dict)
class_weights_dict

{0: 0.5317035512094699, 1: 8.385551948051948}

In [14]:
# from imblearn.over_sampling import SMOTE
# x_train, y_train = SMOTE().fit_resample(x_train, y_train)

In [15]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
print(f"+ X_train: {len(x_train)}")
for fold, (train_idx, valid_idx) in enumerate(kfold.split(x_train, y_train)):
    print(f'Fold {fold}: ')
    print(f'+ train_idx: {train_idx}')
    print(f'+ valid_idx: {valid_idx}')
    print(f'+ train / valid: {valid_idx}')
    pass

+ X_train: 10331
Fold 0:
+ train_idx: [    1     2     4 ... 10327 10328 10330]
+ valid_idx: [    0     3     8 ... 10320 10324 10329]
+ train / valid: [    0     3     8 ... 10320 10324 10329]
Fold 1:
+ train_idx: [    0     1     2 ... 10327 10328 10329]
+ valid_idx: [   12    17    26 ... 10321 10325 10330]
+ train / valid: [   12    17    26 ... 10321 10325 10330]
Fold 2:
+ train_idx: [    0     1     3 ... 10328 10329 10330]
+ valid_idx: [    2    15    27 ... 10310 10311 10327]
+ train / valid: [    2    15    27 ... 10310 10311 10327]
Fold 3:
+ train_idx: [    0     1     2 ... 10328 10329 10330]
+ valid_idx: [    6     7    18 ... 10322 10323 10326]
+ train / valid: [    6     7    18 ... 10322 10323 10326]
Fold 4:
+ train_idx: [    0     2     3 ... 10327 10329 10330]
+ valid_idx: [    1     4     5 ... 10318 10319 10328]
+ train / valid: [    1     4     5 ... 10318 10319 10328]

In [16]:
# for column in outliers_list:
#     data_test = remove_outliers_iqr(data_test, column)
# data_test['collision_type'].replace('?',np.nan,inplace=True)
# data_test['collision_type'].fillna(method='ffill',inplace=True)
# data_test[['property_damage','police_report_available']].replace('?','Unknow',inplace=True)
# (data_test=='?').sum()
scaled_df = scaleColumns(test_con,['PERFORM_CNS_SCORE','PRI_ACTIVE_ACCTS', 'PRI_CURRENT_BALANCE', 
                                 'PRI_DISBURSED_AMOUNT', 'SEC_NO_OF_ACCTS', 'SEC_OVERDUE_ACCTS', 
                                 'SEC_CURRENT_BALANCE', 'PRIMARY_INSTAL_AMT', 'SEC_INSTAL_AMT',
                                 'DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS', 'CREDIT_HISTORY_LENGTH', 
                                 'NO_OF_INQUIRIES', 'DISBURSED_AMOUNT_new',
                                 'ASSET_COST_new', 'LTV_new', 'age', 'disbursal_time'])

test_dummy = pd.get_dummies(scaled_df, prefix_sep='_', drop_first=True)
y_test = test_dummy[['LOAN_DEFAULT']]
x_test= test_dummy.loc[:, test_dummy.columns != 'LOAN_DEFAULT']
x_test.to_csv(f'{save_dir}/x_test.csv', index=False)
y_test.to_csv(f'{save_dir}/y_test.csv', index=False)